spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:h2:~/study
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: utf-8

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: Y29tLWNvZGV0ZXN0LWpvYmlzLXNlY3JldC1jb20tY29kZXRlc3Qtam9iaXMtc2VjcmV0LWNvbS1jb2RldGVzdC1qb2Jpcy1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.SQL: debug
